### ISSUE TITLE
是否是旋转框检测

### ISSUE THREAD

**Issue by wang-TJ-20** [hjk9984/PIoU_YOLOV3#1]
您好，您这个是用来进行旋转框检测的吗，如果是的话，数据集怎样处理的

**Comment by hjk9984** [comment]
Hi, I guess you mistake **Perimeter IoU Loss** for **Pixel IoU Loss**. This repo is for Perimeter IoU Loss and this loss can't be used on rotated object.

P.s. I can't read Chinese. If you ask me in English, I understand what you mean very well. :)
